### ISSUE TITLE
set rvmrc attributes for specific users

### ISSUE THREAD

**Issue by stepheneb** [martinisoft/chef-rvm#107]
I've not been able to find a way in my json meta-data to get rvm-chef to set the some of the rvm settings:

I'd like to be able to set these for the deploy user.

  rvm_project_rvmrc
  rvm_gemset_create_on_use_flag
  rvm_trust_rvmrcs_flag

Here's the full json meta-data file: https://github.com/concord-consortium/littlechef-servers/blob/ruby-lab-server/roles/lab-server.json

I'm specifying: "recipe[rvm::system]" in the json.

And here's just the rvm section:

    "rvm": {
      "default_ruby": "ruby-1.9.3-p194",
      "rvmc": {
        "rvm_project_rvmrc":             1,
        "rvm_gemset_create_on_use_flag": 1,
        "rvm_trust_rvmrcs_flag":         1,
        "group_users": [ "deploy" ]
      },
      "user_installs": [
        {
          "user": "deploy",
          "rvm_project_rvmrc":             1,
          "rvm_gemset_create_on_use_flag": 1,
          "rvm_trust_rvmrcs_flag":         1
        }
      ]
    },

Under the user_installs section I was hoping to be able to set those rvm variables

I AM seeing some variable written into ~/.rvmrc for the deploy user:

    $ cat  /home/deploy/.rvmrc

    # rvm configuration
    #
    # Generated by Chef for ip-10-32-174-243.ec2.internal
    # Local modifications will be overwritten.
    #
    export rvm_path="/home/deploy/.rvm"

    export rvm_gem_options="--no-rdoc --no-ri"

Is this a bug, or am I misunderstanding something, or is this feature not implemented?

Thanks

**Comment by cmluciano** [comment]
@stepheneb Can I close this issue?

**Comment by stepheneb** [comment]
Sure, I can't confirm it;s fixed but if I find I can still reproduce it later I'll re-open it. Thanks

**Comment by cmluciano** [comment]
Thanks @stepheneb
