### ISSUE TITLE
Enhancement: parameterize user install or provide resource

### ISSUE THREAD

**Issue by ahamid** [martinisoft/chef-rvm#114]
Right now all user installs are made in a single pass via the user or user_install recipe.  This makes it complicated (impossible) for recipes to define users and also configure user RVMs (at least on the initial pass).

RecipeA -> define UserA; rvm_gem 'foo' { user 'UserA' }

if rvm:user is run before RecipeB it will fail because UserB does not exist.  if run rvm_gem will fail because rvm has not been installed

**Comment by cmluciano** [comment]
@ahamid All contributions are welcome. That said, we are in the midst of rewriting this cookbook to become a full LWRP cookbook.

Looking at the prior issue it seems that it is expected to fail if the user does not exist, so all logic for creating the user should be placed before the rvm recipe. 

Feel free to open up another issue or PR if you are still experiencing this.
