### ISSUE TITLE
Why rvm installation is not resource, but recipe?

### ISSUE THREAD

**Issue by niquola** [martinisoft/chef-rvm#131]
Is there some reason why  rvm installation is implemented as recipie, but not resource?

It would be nice to have:

<pre>
<code>
  user_rvm "developer" do
       rubies ["1.8.7", "1.9.3"]
       action :install
  end
</code>
</pre>
and reuse it in recipies

**Comment by cmluciano** [comment]
@niquola We are working on this for the next major release.
