### ISSUE TITLE
nil ruby_string when installing global gems using RVM 1.16.17

### ISSUE THREAD

**Issue by tdg5** [martinisoft/chef-rvm#135]
> [2012-10-28T08:50:15-04:00] INFO: Processing execute[install user RVM for chef] action run (rvm::user_install line 76)
> [2012-10-28T08:50:16-04:00] DEBUG: Skipping execute[install user RVM for chef] due to not_if command `bash -c "source /home/chef/.rvm/scripts/rvm && type rvm | cat | head -1 | grep -q '^rvm is a function$'"`
> [2012-10-28T08:50:16-04:00] INFO: Processing execute[upgrade user RVM for chef to none] action run (rvm::user_install line 110)
> [2012-10-28T08:50:16-04:00] DEBUG: Skipping execute[upgrade user RVM for chef to none] due to not_if ruby block
> [2012-10-28T08:50:16-04:00] INFO: Processing rvm_ruby[1.9.3-p286] action install (rvm::user line 170)
> [2012-10-28T08:50:16-04:00] DEBUG: Fetching canonical RVM string for: 1.9.3-p286 (chef)
> [2012-10-28T08:50:16-04:00] DEBUG: Canonical RVM string is: 1.9.3-p286 => ruby-1.9.3-p286 (chef)
> [2012-10-28T08:50:16-04:00] DEBUG: RVM::Shell::ChefWrapper subprocess executing with environment of: [{:user=>"chef", :environment=>{"USER"=>"chef", "HOME"=>"/home/chef"}}].
> [2012-10-28T08:50:16-04:00] DEBUG: RVM::Shell::ChefWrapper silently executing: [source '/var/lib/gems/1.9.1/gems/rvm-1.11.3.5/lib/rvm/shell/shell_wrapper.sh'; __rvm_show_command_epilog]
> [2012-10-28T08:50:17-04:00] DEBUG: RVM::Shell::ChefWrapper silently executing: [export rvm_path='/home/chef/.rvm'; __rvm_show_command_epilog]
> [2012-10-28T08:50:17-04:00] DEBUG: RVM::Shell::ChefWrapper silently executing: [source '/home/chef/.rvm/scripts/rvm'; __rvm_show_command_epilog]
> [2012-10-28T08:50:17-04:00] DEBUG: RVM::Shell::ChefWrapper silently executing: [rvm 'use' 'default'; __rvm_show_command_epilog]
> [2012-10-28T08:50:17-04:00] DEBUG: RVM::Shell::ChefWrapper executing: [rvm 'list' 'strings'; __rvm_show_command_epilog]
> [2012-10-28T08:50:19-04:00] DEBUG: rvm_ruby[ruby-1.9.3-p286] is already installed, so skipping
> [2012-10-28T08:50:19-04:00] INFO: Processing rvm_default_ruby[1.9.3-p286] action create (rvm::user line 177)
> [2012-10-28T08:50:19-04:00] DEBUG: RVM::Shell::ChefWrapper subprocess executing with environment of: [{:user=>"chef", :environment=>{"USER"=>"chef", "HOME"=>"/home/chef"}}].
> [2012-10-28T08:50:19-04:00] DEBUG: RVM::Shell::ChefWrapper silently executing: [source '/var/lib/gems/1.9.1/gems/rvm-1.11.3.5/lib/rvm/shell/shell_wrapper.sh'; __rvm_show_command_epilog]
> [2012-10-28T08:50:20-04:00] DEBUG: RVM::Shell::ChefWrapper silently executing: [export rvm_path='/home/chef/.rvm'; __rvm_show_command_epilog]
> [2012-10-28T08:50:20-04:00] DEBUG: RVM::Shell::ChefWrapper silently executing: [source '/home/chef/.rvm/scripts/rvm'; __rvm_show_command_epilog]
> [2012-10-28T08:50:20-04:00] DEBUG: RVM::Shell::ChefWrapper silently executing: [rvm 'use' 'default'; __rvm_show_command_epilog]
> [2012-10-28T08:50:20-04:00] DEBUG: RVM::Shell::ChefWrapper executing: [rvm 'list' 'default' 'string'; __rvm_show_command_epilog]
> [2012-10-28T08:50:25-04:00] DEBUG: Chef::Provider::RvmDefaultRuby: `ruby-1.9.3-p286' is already default, so skipping
> [2012-10-28T08:50:25-04:00] INFO: Processing rvm_global_gem[bundler] action install (rvm::user line 183)
> [2012-10-28T08:50:25-04:00] INFO: Processing execute[Add bundler to /home/chef/.rvm/gemsets/global.gems] action run (/var/chef/current/cookbooks/rvm/providers/global_gem.rb line 79)
> [2012-10-28T08:50:25-04:00] DEBUG: Skipping execute[Add bundler to /home/chef/.rvm/gemsets/global.gems] due to not_if command `grep -q "^bundler" "/home/chef/.rvm/gemsets/global.gems"`
> [2012-10-28T08:50:25-04:00] DEBUG: RVM::Shell::ChefWrapper subprocess executing with environment of: [{:user=>"chef", :environment=>{"USER"=>"chef", "HOME"=>"/home/chef"}}].
> [2012-10-28T08:50:25-04:00] DEBUG: RVM::Shell::ChefWrapper silently executing: [source '/var/lib/gems/1.9.1/gems/rvm-1.11.3.5/lib/rvm/shell/shell_wrapper.sh'; __rvm_show_command_epilog]
> [2012-10-28T08:50:25-04:00] DEBUG: RVM::Shell::ChefWrapper silently executing: [export rvm_path='/home/chef/.rvm'; __rvm_show_command_epilog]
> [2012-10-28T08:50:25-04:00] DEBUG: RVM::Shell::ChefWrapper silently executing: [source '/home/chef/.rvm/scripts/rvm'; __rvm_show_command_epilog]
> [2012-10-28T08:50:25-04:00] DEBUG: RVM::Shell::ChefWrapper silently executing: [rvm 'use' 'default'; __rvm_show_command_epilog]
> [2012-10-28T08:50:25-04:00] DEBUG: RVM::Shell::ChefWrapper executing: [rvm 'list' 'strings'; __rvm_show_command_epilog]
> [2012-10-28T08:50:28-04:00] INFO: Processing rvm_gem[bundler] action install (/var/chef/current/cookbooks/rvm/providers/global_gem.rb line 48)
> [2012-10-28T08:50:28-04:00] DEBUG: rvm_gem[bundler] using gem from running ruby environment
> [2012-10-28T08:50:30-04:00] DEBUG: RVM version = 1.16.17 (chef)
> [2012-10-28T08:50:33-04:00] DEBUG: Re-raising exception: Mixlib::ShellOut::ShellCommandFailed - rvm_global_gem[bundler] (rvm::user line 183) had an error: Mixlib::ShellOut::ShellCommandFailed: rvm_gem[bundler] (/var/chef/current/cookbooks/rvm/providers/global_gem.rb line 48) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
> ---- Begin output of bash -c "source /home/chef/.rvm/scripts/rvm && rvm nil@global do gem env gempath" ----
> STDOUT: 
> STDERR: Ruby nil@global is not installed.
> ---- End output of bash -c "source /home/chef/.rvm/scripts/rvm && rvm nil@global do gem env gempath" ----
> Ran bash -c "source /home/chef/.rvm/scripts/rvm && rvm nil@global do gem env gempath" returned 1
> /var/lib/gems/1.9.1/gems/mixlib-shellout-1.1.0/lib/mixlib/shellout.rb:248:in `invalid!'
>   /var/lib/gems/1.9.1/gems/mixlib-shellout-1.1.0/lib/mixlib/shellout.rb:234:in `error!'
>   /var/lib/gems/1.9.1/gems/chef-10.14.2/lib/chef/mixin/shell_out.rb:36:in `shell_out!'
>   /var/chef/current/cookbooks/rvm/libraries/rvm_rubygems_package.rb:64:in `gem_paths'
>   /var/lib/gems/1.9.1/gems/chef-10.14.2/lib/chef/provider/package/rubygems.rb:271:in `gem_specification'
>   /var/lib/gems/1.9.1/gems/chef-10.14.2/lib/chef/provider/package/rubygems.rb:89:in `installed_versions'
>   /var/lib/gems/1.9.1/gems/chef-10.14.2/lib/chef/provider/package/rubygems.rb:419:in `matching_installed_versions'
>   /var/lib/gems/1.9.1/gems/chef-10.14.2/lib/chef/provider/package/rubygems.rb:402:in `current_version'
>   /var/lib/gems/1.9.1/gems/chef-10.14.2/lib/chef/provider/package/rubygems.rb:435:in `load_current_resource'
>   /var/lib/gems/1.9.1/gems/chef-10.14.2/lib/chef/provider.rb:102:in `run_action'
>   /var/lib/gems/1.9.1/gems/chef-10.14.2/lib/chef/resource.rb:593:in `run_action'
>   /var/chef/current/cookbooks/rvm/providers/global_gem.rb:57:in `gem_package_wrapper'
>   /var/chef/current/cookbooks/rvm/providers/global_gem.rb:35:in `block (3 levels) in class_from_file'
>   /var/chef/current/cookbooks/rvm/providers/global_gem.rb:34:in `each'
>   /var/chef/current/cookbooks/rvm/providers/global_gem.rb:34:in `block (2 levels) in class_from_file'
>   /var/lib/gems/1.9.1/gems/chef-10.14.2/lib/chef/provider.rb:207:in `instance_eval'
>   /var/lib/gems/1.9.1/gems/chef-10.14.2/lib/chef/provider.rb:207:in `block in action'
>   /var/lib/gems/1.9.1/gems/chef-10.14.2/lib/chef/provider.rb:123:in `run_action'
>   /var/lib/gems/1.9.1/gems/chef-10.14.2/lib/chef/resource.rb:593:in `run_action'
>   /var/lib/gems/1.9.1/gems/chef-10.14.2/lib/chef/runner.rb:49:in `run_action'
>   /var/lib/gems/1.9.1/gems/chef-10.14.2/lib/chef/runner.rb:81:in `block (2 levels) in converge'
>   /var/lib/gems/1.9.1/gems/chef-10.14.2/lib/chef/runner.rb:81:in `each'
>   /var/lib/gems/1.9.1/gems/chef-10.14.2/lib/chef/runner.rb:81:in `block in converge'
>   /var/lib/gems/1.9.1/gems/chef-10.14.2/lib/chef/resource_collection.rb:94:in `block in execute_each_resource'
>   /var/lib/gems/1.9.1/gems/chef-10.14.2/lib/chef/resource_collection/stepable_iterator.rb:116:in `call'
>   /var/lib/gems/1.9.1/gems/chef-10.14.2/lib/chef/resource_collection/stepable_iterator.rb:116:in `call_iterator_block'
>   /var/lib/gems/1.9.1/gems/chef-10.14.2/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
>   /var/lib/gems/1.9.1/gems/chef-10.14.2/lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
>   /var/lib/gems/1.9.1/gems/chef-10.14.2/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
>   /var/lib/gems/1.9.1/gems/chef-10.14.2/lib/chef/resource_collection.rb:92:in `execute_each_resource'
>   /var/lib/gems/1.9.1/gems/chef-10.14.2/lib/chef/runner.rb:80:in `converge'
>   /var/lib/gems/1.9.1/gems/chef-10.14.2/lib/chef/client.rb:378:in `converge'
>   /var/lib/gems/1.9.1/gems/chef-10.14.2/lib/chef/client.rb:420:in `do_run'
>   /var/lib/gems/1.9.1/gems/chef-10.14.2/lib/chef/client.rb:176:in `run'
>   /var/lib/gems/1.9.1/gems/chef-10.14.2/lib/chef/application/solo.rb:230:in `block in run_application'
>   /var/lib/gems/1.9.1/gems/chef-10.14.2/lib/chef/application/solo.rb:218:in `loop'
>   /var/lib/gems/1.9.1/gems/chef-10.14.2/lib/chef/application/solo.rb:218:in `run_application'
>   /var/lib/gems/1.9.1/gems/chef-10.14.2/lib/chef/application.rb:70:in `run'
>   /var/lib/gems/1.9.1/gems/chef-10.14.2/bin/chef-solo:25:in `<top (required)>'
>   /usr/local/bin/chef-solo:19:in `load'
>   /usr/local/bin/chef-solo:19:in `<main>'

Using ruby-1.9.3p286 on Ubuntu 12.04 Server. No issue with RVM pinned to 1.16.16.

**Comment by cmluciano** [comment]
This appears to be fixed [upstream](https://github.com/wayneeseguin/rvm/issues/1266). Please reopen if you are having problems.
