### ISSUE TITLE
uninitialized constant RVM::ChefUserEnvironment on Ubuntu Precise

### ISSUE THREAD

**Issue by ghost** [martinisoft/chef-rvm#141]
I experience some issues when using your rvm cookbook with ubuntu precise with chef-10.16.2-1 (clean install, tested multiple times), rvm current HEAD.

when using the lwrp in my recipe, chef-client fails

<pre>
rvm_default_ruby 'ruby-1.9.3-p194'
</pre>

leads to the following error

<pre>
[Thu, 22 Nov 2012 11:49:31 +0100] INFO: Processing rvm_default_ruby[ruby-1.9.3-p194] action create (mycookbook::default line 21)

================================================================================
Error executing action `create` on resource 'rvm_default_ruby[ruby-1.9.3-p194]'
================================================================================

NameError
---------
uninitialized constant RVM::ChefUserEnvironment

Cookbook Trace:
---------------
/var/cache/chef/cookbooks/rvm/providers/default_ruby.rb:29:in `load_current_resource'

Resource Declaration:
---------------------
# In /var/cache/chef/cookbooks/mycookbook/recipes/default.rb

 21: rvm_default_ruby 'ruby-1.9.3-p194'

Compiled Resource:
------------------
# Declared in /var/cache/chef/cookbooks/mycookbook/recipes/default.rb:21:in `from_file'

rvm_default_ruby("ruby-1.9.3-p194") do
  cookbook_name "mycookbook"
  ruby_string "ruby-1.9.3-p194"
  action :create
  retry_delay 2
  recipe_name "default"
  retries 0
end
</pre>

Furthermore, when running

<pre>
chef-client -o recipe[rvm::system]
</pre>

I get the following

<pre>
[Thu, 22 Nov 2012 11:55:27 +0100] INFO: Processing rvm_gem[bundler] action install (/var/cache/chef/cookbooks/rvm/providers/global_gem.rb line 48)

================================================================================
Error executing action `install` on resource 'rvm_gem[bundler]'
================================================================================

Mixlib::ShellOut::ShellCommandFailed
------------------------------------
Expected process to exit with [0], but received '1'
---- Begin output of bash -c "source /etc/profile.d/rvm.sh && rvm nil@global do gem env gempath" ----
STDOUT: 
STDERR: Ruby nil@global is not installed.
---- End output of bash -c "source /etc/profile.d/rvm.sh && rvm nil@global do gem env gempath" ----
Ran bash -c "source /etc/profile.d/rvm.sh && rvm nil@global do gem env gempath" returned 1

Cookbook Trace:
---------------
/var/cache/chef/cookbooks/rvm/libraries/rvm_rubygems_package.rb:64:in `gem_paths'
/var/cache/chef/cookbooks/rvm/providers/global_gem.rb:57:in `gem_package_wrapper'
/var/cache/chef/cookbooks/rvm/providers/global_gem.rb:35:in `class_from_file'
/var/cache/chef/cookbooks/rvm/providers/global_gem.rb:34:in `each'
/var/cache/chef/cookbooks/rvm/providers/global_gem.rb:34:in `class_from_file'

Resource Declaration:
---------------------
# In /var/cache/chef/cookbooks/rvm/providers/global_gem.rb

 48:   g = rvm_gem new_resource.package_name do
 49:     ruby_string ruby_global_gemset
 50:     source      new_resource.source if new_resource.source
 51:     options     new_resource.options if new_resource.options
 52:     version     new_resource.version if new_resource.version
 53:     gem_binary  new_resource.gem_binary if new_resource.gem_binary
 54:     user        new_resource.user
 55:     action      :nothing
 56:   end
 57:   g.run_action(exec_action)

Compiled Resource:
------------------
# Declared in /var/cache/chef/cookbooks/rvm/providers/global_gem.rb:48:in `gem_package_wrapper'

rvm_gem("bundler") do
  cookbook_name "rvm"
  provider Chef::Provider::Package::RVMRubygems
  action [:nothing]
  ruby_string "nil@global"
  retry_delay 2
  package_name "bundler"
  retries 0
end

================================================================================
Error executing action `install` on resource 'rvm_global_gem[bundler]'
================================================================================

Mixlib::ShellOut::ShellCommandFailed
------------------------------------
rvm_gem[bundler] (/var/cache/chef/cookbooks/rvm/providers/global_gem.rb line 48) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
---- Begin output of bash -c "source /etc/profile.d/rvm.sh && rvm nil@global do gem env gempath" ----
STDOUT: 
STDERR: Ruby nil@global is not installed.
---- End output of bash -c "source /etc/profile.d/rvm.sh && rvm nil@global do gem env gempath" ----
Ran bash -c "source /etc/profile.d/rvm.sh && rvm nil@global do gem env gempath" returned 1

Cookbook Trace:
---------------
/var/cache/chef/cookbooks/rvm/libraries/rvm_rubygems_package.rb:64:in `gem_paths'
/var/cache/chef/cookbooks/rvm/providers/global_gem.rb:57:in `gem_package_wrapper'
/var/cache/chef/cookbooks/rvm/providers/global_gem.rb:35:in `class_from_file'
/var/cache/chef/cookbooks/rvm/providers/global_gem.rb:34:in `each'
/var/cache/chef/cookbooks/rvm/providers/global_gem.rb:34:in `class_from_file'

Resource Declaration:
---------------------
# In /var/cache/chef/cookbooks/rvm/libraries/chef_rvm_recipe_helpers.rb

189:           rvm_global_gem gem[:name] do
190:             user      opts[:user]
191:             [:version, :action, :options, :source].each do |attr|
192:               send(attr, gem[attr]) if gem[attr]
193:             end
194:           end
195:         end

Compiled Resource:
------------------
# Declared in /var/cache/chef/cookbooks/rvm/libraries/chef_rvm_recipe_helpers.rb:189:in `install_rubies'

rvm_global_gem("bundler") do
  cookbook_name "rvm"
  action :install
  retry_delay 2
  package_name "bundler"
  recipe_name "system"
  retries 0
end

[Thu, 22 Nov 2012 11:55:27 +0100] ERROR: Running exception handlers
[Thu, 22 Nov 2012 11:55:27 +0100] FATAL: Saving node information to /var/cache/chef/failed-run-data.json
[Thu, 22 Nov 2012 11:55:27 +0100] ERROR: Exception handlers complete
[Thu, 22 Nov 2012 11:55:28 +0100] FATAL: Stacktrace dumped to /var/cache/chef/chef-stacktrace.out
[Thu, 22 Nov 2012 11:55:28 +0100] FATAL: Mixlib::ShellOut::ShellCommandFailed: rvm_global_gem[bundler] (rvm::system line 189) had an error: Mixlib::ShellOut::ShellCommandFailed: rvm_gem[bundler] (/var/cache/chef/cookbooks/rvm/providers/global_gem.rb line 48) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
---- Begin output of bash -c "source /etc/profile.d/rvm.sh && rvm nil@global do gem env gempath" ----
STDOUT: 
STDERR: Ruby nil@global is not installed.
---- End output of bash -c "source /etc/profile.d/rvm.sh && rvm nil@global do gem env gempath" ----
Ran bash -c "source /etc/profile.d/rvm.sh && rvm nil@global do gem env gempath" returned 1
</pre>

This seems to be a bug, unless I'm doing something horribly wrong?
Thanks for your work on this cookbook :)

**Comment by cmluciano** [comment]
I think this ended up being an rvm issue. PLease re-open if you are still experiencing it
