### ISSUE TITLE
Allow explicit binary packages for install

### ISSUE THREAD

**Issue by mperham** [martinisoft/chef-rvm#155]
In order to minimize network dependencies/downloads, I'd like to give RVM a binary ruby package to install rather than have it download one every time.

It looks like `rvm mount -r ./ruby-1.9.3-p374.tar.bz2` works for the binary packages hosted at rvm.io.  Is there some way to do this with chef-rvm or an alternative to achieve the same?

**Comment by cmluciano** [comment]
This should be working now with this [commit](https://github.com/martinisoft/chef-rvm/commit/8d40c777c46b713318fb8f68060f4d5fa5f6a886). Please reopen if this is still an issue.
