### ISSUE TITLE
Failed to install rvm_ruby[ruby-1.9.3-p327]. Check logs in /log/ruby-1.9.3-p327

### ISSUE THREAD

**Issue by polivers** [martinisoft/chef-rvm#159]
When I try to install ruby, I get the error message(s) 

"INFO: Building rvm_ruby[ruby-1.9.3-p327], this could take awhile..."
"WARN: Failed to install rvm_ruby[ruby-1.9.3-p327]. Check logs in /log/ruby-1.9.3-p327"
"INFO: rvm_ruby[ruby-1.9.3-p327] build time was 0.04745973151666667 minutes."
"INFO: Setting default ruby to rvm_ruby[ruby-1.9.3-p327]"

My chef role has the following rvm attributes: 
"rvm"=>{
    "default_ruby" => 'ruby-1.9.3-p374',
    "user_installs" => [
        {'user'=>'dev', 'user_default_ruby'=>'ruby-1.9.3-p374', 'rubies'=>['ruby-1.9.3-p374']}
    ]
}

There's no /log directory, so I can't debug the problem. 

Any idea's what's going wrong?

**Comment by alambike** [comment]
Hi @brauliobo , I have no issue right now nor with rvm.io certificate, can you paste the details of error?

**Comment by cmluciano** [comment]
This seems to be fixed [upstream](https://tickets.opscode.com/browse/BENTO-109). Please reopen this issue if you are still having problems.

**Comment by spuder** [comment]
Unfortunately none of the 3 work arounds suggested are working for me

https://github.com/martinisoft/chef-rvm/issues/159#issuecomment-16009180

https://github.com/martinisoft/chef-rvm/issues/159#issuecomment-19242629

https://github.com/martinisoft/chef-rvm/issues/159#issuecomment-25045578

Also tried using the cookbook from the latest commit in the berks file 08ec265f277e112a5a2e4b201bd32ddfe1bb968c

Is anyone who is successfully using this cookbook willing to post their runlist / default attributes / berks file? 

```
suites:
  - name: default
    run_list:
      - recipe[apt]
      - recipe[rvm::system]
```
```
    [2015-07-14T19:47:44+00:00] WARN: chef_gem[rvm] chef_gem compile_time installation is deprecated
       [2015-07-14T19:47:44+00:00] WARN: chef_gem[rvm] Please set `compile_time false` on the resource to use the new behavior.
       [2015-07-14T19:47:44+00:00] WARN: chef_gem[rvm] or set `compile_time true` on the resource if compile_time behavior is required.
       Recipe: rvm::default
         * chef_gem[rvm] action install
           - install version >= 1.11.3.6 of package rvm
       /tmp/kitchen/cookbooks/rvm/libraries/rvm_chef_user_environment.rb:49: warning: class variable access from toplevel

         ================================================================================
         Recipe Compile Error in /tmp/kitchen/cookbooks/rvm/recipes/system.rb
         ================================================================================

         NoMethodError
         -------------
         undefined method `[]' for nil:NilClass

         Cookbook Trace:
         ---------------
           /tmp/kitchen/cookbooks/rvm/recipes/system_install.rb:33:in `from_file'
           /tmp/kitchen/cookbooks/rvm/recipes/system.rb:20:in `from_file'

         Relevant File Content:
         ----------------------
         /tmp/kitchen/cookbooks/rvm/recipes/system_install.rb:
```

**Comment by margold** [comment]
I had the same problem. What was happening in my case is that one of the previous steps, which fetched and installed rvm, failed because `https://get.rvm.io` could not be resolved, but didn't cause the recipe to stop. Then, when the recipe attempts to execute `/etc/profile.d/rvm.sh`, it fails, because the file is not there.

You can check if that's the case for you by running `dig @your-nameserver get.rvm.io`.
