### ISSUE TITLE
chef-client not usable after bootstrap with recipe rvm::system

### ISSUE THREAD

**Issue by apsoto** [martinisoft/chef-rvm#175]
I've bootstrapped an ubuntu 10.04 system with rvm::system in the run list.

chef 11..4.0 was installed to /opt/chef

Now chef-client doesn't run.  For the time being I've manually installed chef into the global gemset (which I will roll into my recipe later), but I'm wondering if anyone knows of a supported way to get this to work without using a custom bootstrap as @fnichol mentions in #91?  Or is installing chef gems into the global gemset the best there is for the time being?

Thanks

**Comment by cmluciano** [comment]
Is this still an issue?

**Comment by apsoto** [comment]
Probably, as I still have the same recipes in production.  However, I've found another workaround by changing rubies by running `rvm system`.  Then chef is able to find it's embedded ruby.

**Comment by cmluciano** [comment]
Ok, closing this for now
