### ISSUE TITLE
make rvm available directly after install

### ISSUE THREAD

**Issue by grosser** [martinisoft/chef-rvm#176]
After an vagrant up rvm executable is not yet available, so I had to add this hack, would be nice if it was just there (I could use the full path, but it's just nice if first run and second run are consistent)

```
include_recipe "rvm::system"

ENV["PATH"] += ":/usr/local/rvm/bin" # make rvm work right after being installed

bash "create rvm wrappers" do
  code("rvm wrapper ruby-1.9.3-p392 ruby_193")
end
```

**Comment by cmluciano** [comment]
Is this still an issue for you?

**Comment by poloka** [comment]
Yes, RVM is not being sourced for usage on a fresh install.  Can recreate
overtime by creating a fresh Vagrant box, run the RVM cookbook and try to
execute a shell command for RVM it is not accessible.  This is what I have
in my LWRP:

  bash 'install gem dependencies for the server' do
    code <<-EOH
    cd #{node.default[new_resource.name][:dir]}
    source #{new_resource.rvm_directory}
    rvm use #{new_resource.ruby_version}@myserver && bundle install
--without development test
    EOH
  end

**Comment by cmluciano** [comment]
I am not seeing this issue.

attributes/default
```
  default['rvm']['user_installs'] = [
     {
       user: 'vagrant',
       rvmrc: {
         rvm_trust_rvmrcs_flag: 1,
         rvm_use_flag: 2,
         rvm_pretty_print_flag: 1,
         rvm_gemset_create_on_use_flag: 1,
        rvm_autolibs_flag: :disabled
      }
    }
]
```
recipe/default
```
include_recipe "apt"
include_recipe 'rvm::user_install' 
```

If you are still experiencing this problem, please reopen another issue and gist an example of your code.
