### ISSUE TITLE
No rubies installed because package dependencies

### ISSUE THREAD

**Issue by avances123** [martinisoft/chef-rvm#185]
Im installing with vagrant in ubuntu 12.04, and the cookbook end with no error but no rubies install in ```rvm list``` (system install all by default)

No log written in /usr/local/rvm/log

The packages are ```libgdbm-dev pkg-config libffi-dev```

basebox was installed with ruby 1.9.2 from source to bootstrap chef.

**Comment by cmluciano** [comment]
I think this should be fixed with providers/ruby installing the necessary packages. RVM is also workign on a more elegant solution for this.
