### ISSUE TITLE
NameError: Cannot find a resource for create_rvm_shell_chef_wrapper on ubuntu version 10.10

### ISSUE THREAD

**Issue by amolpujari** [martinisoft/chef-rvm#190]
================================================================================
Recipe Compile Error in /home/amol/app_dir/chef/solo/custom_cookbooks/app_name/recipes/default.rb
================================================================================

NameError
---------
Cannot find a resource for create_rvm_shell_chef_wrapper on ubuntu version 10.10

Cookbook Trace:
---------------
  /home/amol/app_dir/chef/solo/cookbooks/rvm/recipes/default.rb:28:in `from_file'
  /home/amol/app_dir/chef/solo/custom_cookbooks/app_name/recipes/default.rb:1:in `from_file'

Relevant File Content:
----------------------
/home/amol/app_dir/chef/solo/cookbooks/rvm/recipes/default.rb:

 21:  gem_package 'rvm' do
 22:    action :nothing
 23:  end.run_action(:install)
 24:  
 25:  require 'rubygems'
 26:  Gem.clear_paths
 27:  require 'rvm'
 28>> create_rvm_shell_chef_wrapper
 29:  create_rvm_chef_user_environment
 30:  
 31:  class Chef::Resource
 32:    # mix in #rvm_cmd_wrap helper into resources
 33:    include Chef::RVM::ShellHelpers
 34:  end
 35:  
 36:  class Chef::Recipe
 37:    # mix in recipe helpers

[2013-04-23T15:44:35+05:30] DEBUG: Re-raising exception: NameError - Cannot find a resource for create_rvm_shell_chef_wrapper on ubuntu version 10.10
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.4.2/lib/chef/resource_platform_map.rb:126:in `get'
  /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.4.2/lib/chef/resource.rb:761:in `resource_for_platform'
  /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.4.2/lib/chef/resource.rb:778:in `resource_for_node'
  /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.4.2/lib/chef/dsl/recipe.rb:55:in `method_missing'
  /home/amol/app_dir/chef/solo/cookbooks/rvm/recipes/default.rb:28:in `from_file'
  /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.4.2/lib/chef/mixin/from_file.rb:30:in `instance_eval'
  /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.4.2/lib/chef/mixin/from_file.rb:30:in `from_file'
  /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.4.2/lib/chef/cookbook_version.rb:346:in `load_recipe'
  /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.4.2/lib/chef/run_context.rb:151:in `load_recipe'
  /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.4.2/lib/chef/run_context.rb:132:in `block in include_recipe'
  /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.4.2/lib/chef/run_context.rb:131:in `each'
  /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.4.2/lib/chef/run_context.rb:131:in `include_recipe'
  /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.4.2/lib/chef/dsl/include_recipe.rb:26:in `include_recipe'
  /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.4.2/lib/chef/dsl/include_recipe.rb:35:in `require_recipe'
  /home/amol/app_dir/chef/solo/custom_cookbooks/app_name/recipes/default.rb:1:in `from_file'
  /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.4.2/lib/chef/mixin/from_file.rb:30:in `instance_eval'
  /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.4.2/lib/chef/mixin/from_file.rb:30:in `from_file'
  /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.4.2/lib/chef/cookbook_version.rb:346:in `load_recipe'
  /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.4.2/lib/chef/run_context.rb:151:in `load_recipe'
  /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.4.2/lib/chef/run_context/cookbook_compiler.rb:139:in `block in compile_recipes'
  /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.4.2/lib/chef/run_context/cookbook_compiler.rb:137:in `each'
  /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.4.2/lib/chef/run_context/cookbook_compiler.rb:137:in `compile_recipes'
  /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.4.2/lib/chef/run_context/cookbook_compiler.rb:74:in `compile'
  /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.4.2/lib/chef/run_context.rb:86:in `load'
  /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.4.2/lib/chef/client.rb:224:in `setup_run_context'
  /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.4.2/lib/chef/client.rb:467:in `do_run'
  /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.4.2/lib/chef/client.rb:200:in `run'
  /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.4.2/lib/chef/application.rb:190:in `run_chef_client'
  /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.4.2/lib/chef/application/solo.rb:239:in `block in run_application'
  /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.4.2/lib/chef/application/solo.rb:231:in `loop'
  /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.4.2/lib/chef/application/solo.rb:231:in `run_application'
  /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.4.2/lib/chef/application.rb:73:in `run'
  /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.4.2/bin/chef-solo:25:in `<top (required)>'
  /usr/bin/chef-solo:23:in `load'
  /usr/bin/chef-solo:23:in `<main>'
[2013-04-23T15:44:35+05:30] ERROR: Running exception handlers
[2013-04-23T15:44:35+05:30] ERROR: Exception handlers complete
Chef Client failed. 1 resources updated
[2013-04-23T15:44:35+05:30] FATAL: Stacktrace dumped to /home/amol/app_dir/chef/solo/chef-stacktrace.out
[2013-04-23T15:44:35+05:30] DEBUG: NameError: Cannot find a resource for create_rvm_shell_chef_wrapper on ubuntu version 10.10
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.4.2/lib/chef/resource_platform_map.rb:126:in `get'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.4.2/lib/chef/resource.rb:761:in `resource_for_platform'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.4.2/lib/chef/resource.rb:778:in `resource_for_node'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.4.2/lib/chef/dsl/recipe.rb:55:in `method_missing'
/home/amol/app_dir/chef/solo/cookbooks/rvm/recipes/default.rb:28:in `from_file'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.4.2/lib/chef/mixin/from_file.rb:30:in `instance_eval'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.4.2/lib/chef/mixin/from_file.rb:30:in `from_file'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.4.2/lib/chef/cookbook_version.rb:346:in `load_recipe'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.4.2/lib/chef/run_context.rb:151:in `load_recipe'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.4.2/lib/chef/run_context.rb:132:in `block in include_recipe'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.4.2/lib/chef/run_context.rb:131:in `each'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.4.2/lib/chef/run_context.rb:131:in `include_recipe'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.4.2/lib/chef/dsl/include_recipe.rb:26:in `include_recipe'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.4.2/lib/chef/dsl/include_recipe.rb:35:in `require_recipe'
/home/amol/app_dir/chef/solo/custom_cookbooks/app_name/recipes/default.rb:1:in `from_file'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.4.2/lib/chef/mixin/from_file.rb:30:in `instance_eval'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.4.2/lib/chef/mixin/from_file.rb:30:in `from_file'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.4.2/lib/chef/cookbook_version.rb:346:in `load_recipe'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.4.2/lib/chef/run_context.rb:151:in `load_recipe'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.4.2/lib/chef/run_context/cookbook_compiler.rb:139:in `block in compile_recipes'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.4.2/lib/chef/run_context/cookbook_compiler.rb:137:in `each'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.4.2/lib/chef/run_context/cookbook_compiler.rb:137:in `compile_recipes'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.4.2/lib/chef/run_context/cookbook_compiler.rb:74:in `compile'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.4.2/lib/chef/run_context.rb:86:in `load'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.4.2/lib/chef/client.rb:224:in `setup_run_context'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.4.2/lib/chef/client.rb:467:in `do_run'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.4.2/lib/chef/client.rb:200:in `run'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.4.2/lib/chef/application.rb:190:in `run_chef_client'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.4.2/lib/chef/application/solo.rb:239:in `block in run_application'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.4.2/lib/chef/application/solo.rb:231:in `loop'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.4.2/lib/chef/application/solo.rb:231:in `run_application'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.4.2/lib/chef/application.rb:73:in `run'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.4.2/bin/chef-solo:25:in `<top (required)>'
/usr/bin/chef-solo:23:in `load'
/usr/bin/chef-solo:23:in `<main>'
[2013-04-23T15:44:35+05:30] FATAL: NameError: Cannot find a resource for create_rvm_shell_chef_wrapper on ubuntu version 10.10

**Comment by cmluciano** [comment]
Solution appears to be depend on RVM. Please reopen if you are still experiencing this issue.
