### ISSUE TITLE
rvm_ruby fails with undefined method `chomp' for nil:NilClass

### ISSUE THREAD

**Issue by ghost** [martinisoft/chef-rvm#193]
<pre>
  * rvm_ruby[1.9.3-p374] action install
================================================================================
Error executing action `install` on resource 'rvm_ruby[1.9.3-p374]'
================================================================================

NoMethodError
-------------
undefined method `chomp' for nil:NilClass

Cookbook Trace:
---------------
/var/chef/cache/cookbooks/rvm/libraries/chef_rvm_string_cache.rb:77:in `canonical_ruby_string'
/var/chef/cache/cookbooks/rvm/libraries/chef_rvm_string_cache.rb:50:in `fetch'
/var/chef/cache/cookbooks/rvm/libraries/chef_rvm_string_helpers.rb:55:in `normalize_ruby_string'
/var/chef/cache/cookbooks/rvm/providers/ruby.rb:26:in `load_current_resource'

Resource Declaration:
---------------------
# In /var/chef/cache/cookbooks/mycookbook/recipes/rvm-test.rb

 23: rvm_ruby '1.9.3-p374' do
 24:   user 'deploy'
 25: end
 26: 

Compiled Resource:
------------------
# Declared in /var/chef/cache/cookbooks/mycookbook/recipes/rvm-test.rb:23:in `from_file'

rvm_ruby("1.9.3-p374") do
  action :install
  retries 0
  retry_delay 2
  cookbook_name "mycookbook"
  recipe_name "rvm-test"
  user "deploy"
  ruby_string "1.9.3-p374"
end
</pre>

On a freshly spawned ubuntu-12.10

**Comment by rb2k** [comment]
I'm currently debugging on this as well. A possible solution: RVM now needs a gpg key installed before running:

```
gpg --keyserver hkp://keys.gnupg.net --recv-keys D39DC0E3
```

(from the rvm site)

The system install does this: https://github.com/fnichol/chef-rvm/blob/87cc2fe108511f45fb78ad86815f1fb35c1aff97/recipes/system_install.rb#L34
Don't think the user one does?

**Comment by brauliobo** [comment]
Adding the gpg keys manually didn't help for me for the user install.

**Comment by rb2k** [comment]
I tried the manual rvm install and had to add them before it succeeded. for me it currently fails when doing this:

```
execute 'Adding gpg key for jenkins' do
  user 'jenkins'
  command "`which gpg2 || which gpg` --keyserver hkp://keys.gnupg.net --recv-keys D39DC0E3"
end
```

(jenkins is the user I install rvm for).

Weirdly enough it fails with:

```
==> default: STDERR: gpg: fatal: can't create directory `/root/.gnupg': Permission denied
```

Manually executing this as the jenkins user works fine.

**Comment by brauliobo** [comment]
@rb2k try specifying `cwd` for execute.

**Comment by BAIS2** [comment]
@rb2k @brauliobo same thing happened to me, even with the `cwd`. I ended up doing [this](https://github.com/fnichol/chef-rvm/issues/288#issue-53328772) (ugly, yes, I know).

Weird thing is, why didn't they add support for user installs and only for [system install](https://github.com/fnichol/chef-rvm/blob/master/recipes/system_install.rb)?

**Comment by lemattma** [comment]
@rb2k @brauliobo same thing happened to me, even with the `cwd`. I ended up doing [this](https://github.com/fnichol/chef-rvm/issues/288#issue-53328772) (ugly, yes, I know).

Weird thing is, why didn't they add support for user installs and only for [system install](https://github.com/fnichol/chef-rvm/blob/master/recipes/system_install.rb)?

**Comment by rb2k** [comment]
yeah, cwd fails over here too :-/

**Comment by lemattma** [comment]
@rb2k did you try what I came up with?

https://github.com/fnichol/chef-rvm/issues/288#issue-53328772

**Comment by cmluciano** [comment]
I think this may have been a combination issue between upstream rvm ssl and depends not being included in the metadata. Please reopen this issue if you are still experiencing it.

**Comment by rottmanj** [comment]
Still seeing this issue

```
================================================================================
    Error executing action `create` on resource 'rvm_gemset[togl-rapi]'
    ================================================================================

    NoMethodError
    -------------
    undefined method `chomp' for nil:NilClass

    Cookbook Trace:
    ---------------
    /var/chef/cache/cookbooks/rvm/libraries/chef_rvm_string_cache.rb:77:in `canonical_ruby_string'
    /var/chef/cache/cookbooks/rvm/libraries/chef_rvm_string_cache.rb:50:in `fetch'
    /var/chef/cache/cookbooks/rvm/libraries/chef_rvm_string_helpers.rb:55:in `normalize_ruby_string'
    /var/chef/cache/cookbooks/rvm/providers/gemset.rb:28:in `load_current_resource'

    Resource Declaration:
    ---------------------
    # In /var/chef/cache/cookbooks/togl_ruby/recipes/default.rb

      3: rvm_gemset "#{node['togl_ruby']['gemset']}" do
      4:   ruby_string   "#{node['togl_ruby']['ruby_string']}"
      5:   action        :create
      6: end
      7:

    Compiled Resource:
    ------------------
    # Declared in /var/chef/cache/cookbooks/togl_ruby/recipes/default.rb:3:in `from_file'

    rvm_gemset("togl-rapi") do
      action [:create]
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      declared_type :rvm_gemset
      cookbook_name "togl_ruby"
      recipe_name "default"
      ruby_string "ruby-2.0.0-p353"
    end

[2015-03-09T17:19:35-07:00] INFO: Running queued delayed notifications before re-raising exception
[2015-03-09T17:19:35-07:00] ERROR: Converge failed with error message rvm_gemset[togl-rapi] (togl_ruby::default line 3) had an error: NoMethodError: undefined method `chomp' for nil:NilClass

Running handlers:
[2015-03-09T17:19:35-07:00] ERROR: Running exception handlers
Running handlers complete
[2015-03-09T17:19:35-07:00] ERROR: Exception handlers complete
[2015-03-09T17:19:35-07:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
Chef Client failed. 4 resources updated in 8.98212668 seconds
[2015-03-09T17:19:35-07:00] INFO: Sending resource update report (run-id: b1fef52b-402a-4bd2-a151-9db8c6e927df)
[2015-03-09T17:19:36-07:00] ERROR: Found 1 errors, they are stored in the backtrace
[2015-03-09T17:19:36-07:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

**Comment by cmluciano** [comment]
@rottmanj Please open another issue with your recipe example.

**Comment by spuder** [comment]
@rottmanj did you open a new issue? 

I'm encountering the same problem, using the simplest of simple uses cases

Happens on both 12.04 and 14.04

kitchen.yml
```
---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[apt]
      - recipe[rvm::system]
    attributes:
```

Throws this error
```
       * execute[install system-wide RVM] action run
           - execute curl -L https://get.rvm.io | bash  -s -- --branch stable --version head
         * execute[upgrade system-wide RVM to none] action run (skipped due to not_if)
       Recipe: rvm::system


           ================================================================================
           Error executing action `create` on resource 'rvm_default_ruby[ruby-1.9.3-p547]'
           ================================================================================

           NoMethodError
           -------------
           undefined method `chomp' for nil:NilClass

           Cookbook Trace:
           ---------------
           /tmp/kitchen/cookbooks/rvm/libraries/chef_rvm_string_cache.rb:77:in `canonical_ruby_string'
           /tmp/kitchen/cookbooks/rvm/libraries/chef_rvm_string_cache.rb:50:in `fetch'
           /tmp/kitchen/cookbooks/rvm/libraries/chef_rvm_string_helpers.rb:55:in `normalize_ruby_string'
           /tmp/kitchen/cookbooks/rvm/providers/default_ruby.rb:26:in `load_current_resource'

           Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cookbooks/rvm/libraries/chef_rvm_recipe_helpers.rb

           185:         rvm_default_ruby opts[:default_ruby] do
           186:           user  opts[:user]
           187:         end
           188:

           Compiled Resource:
           ------------------
           # Declared in /tmp/kitchen/cookbooks/rvm/libraries/chef_rvm_recipe_helpers.rb:185:in `install_rubies'

           rvm_default_ruby("ruby-1.9.3-p547") do
             action :create
             retries 0
             retry_delay 2
             default_guard_interpreter :default
             declared_type :rvm_default_ruby
             cookbook_name :rvm
             recipe_name "system"
             ruby_string "ruby-1.9.3-p547"
           end
```

**Comment by toebbel** [comment]
+1

**Comment by romanvbabenko** [comment]
+1

**Comment by msf0r** [comment]
+1

**Comment by ohadpartuck** [comment]
+1

**Comment by margold** [comment]
Encountered the same issue, in my case it was due to nameserver not being able to resolve `get.rvm.io`: https://github.com/martinisoft/chef-rvm/issues/159#issuecomment-168031113

Using a different nameserver solved the problem.

**Comment by ohadpartuck** [comment]
For me it was just a matter of the get.rvm.io server was unavailable. tried again after a couple of hours and it worked.
