### ISSUE TITLE
No versions of ruby can be installed

### ISSUE THREAD

**Issue by somek** [martinisoft/chef-rvm#199]
I have this in my Chef role: 
```
run_list("recipe[rvm::user]")
default_attributes(
:rvm => {
  :user_installs => [
    'user' => "somek",
    'rubies' => ['ruby-2.0.0-p0']
  ],
  :user_default_ruby => 'ruby-2.0.0-p0',
}) 
```
When deploying on a Vagrant VM, I see the following rvm output:
```
Building rvm_ruby[ruby-2.0.0-p0], this could take awhile...
Failed to install rvm_ruby[ruby-2.0.0-p0]. Check logs in /log/ruby-2.0.0-p0
rvm_ruby[ruby-2.0.0-p0] build time was 0.053249113316666666 minutes.
```

The ~/.rvm/log/ruby-2.0.0-p0 directory in the VM is empty so I've got no idea why the build is failing completely. 
Also tried with different RVM versions (1.19.0, 1.17.10) but can't install ruby-2.0 with any of them. 

This is on Ubuntu 12.04.2.  

Any ideas?

**Comment by cmluciano** [comment]
Dup of #159
