### ISSUE TITLE
rvm not available to rvm group users

### ISSUE THREAD

**Issue by cstewart87** [martinisoft/chef-rvm#253]
After running test-kitchen for the following recipe, the only user with rvm/rubies available is vagrant.  

Only user found in rvm group is 'ubuntu'.  Am I using the correct recipe?

```ruby
node.default['rvm']['group_users'] = ['ubuntu']

include_recipe 'rvm::system'
```

**Comment by cmluciano** [comment]
You should be using the user recipe
