### ISSUE TITLE
Force `rvm install --binary``

### ISSUE THREAD

**Issue by simao** [martinisoft/chef-rvm#265]
Hello,

Is it possible to pass the `--binary`` flag to `rvm install` so that rubies are downloaded instead of compiled? 

Executing `rvm install --binary` on a shell makes rvm download rubies but when running through the cookbooks rubies are compiled.

**Comment by brodock** [comment]
Same as #173

**Comment by cmluciano** [comment]
Duplicated by #173 as @brodock commented.
