### ISSUE TITLE
['dvm']['user_installs'] not compatible with home folder located outside /home (Ubuntu Linux)

### ISSUE THREAD

**Issue by stonevil** [martinisoft/chef-rvm#266]
['dvm']['user_installs'] not compatible with home folder located outside /home (Ubuntu Linux)

Error:
         * template[/home//var/lib/dashing/.rvmrc] action create[2014-08-10T00:10:21+00:00] INFO: Processing template[/home//var/lib/dashing/.rvmrc] action create (rvm::user_install line 145)

    * Parent directory /home//var/lib/dashing does not exist.    
    ================================================================================
    Error executing action `create` on resource 'template[/home//var/lib/dashing/.rvmrc]'
    ================================================================================

**Comment by cmluciano** [comment]
Dup #207
