### ISSUE TITLE
cannot load such file -- rvm error

### ISSUE THREAD

**Issue by eugenemiretsky** [martinisoft/chef-rvm#324]
Hi,

I get the following error when trying to run the system and user cook books.

cannot load such file -- rvm (line 27 of default.rb)

Any ideas?

**Comment by cmluciano** [comment]
Can you gist what your default.rb file is?

**Comment by eugenemiretsky** [comment]
Pulled a fresh copy of default.rb and now it works

**Comment by eugenemiretsky** [comment]
however getting "GPG signature verification failed" error

**Comment by cmluciano** [comment]
Can you copy the full error into here?

**Comment by cmluciano** [comment]
Also what does your default.rb run-list look like?

**Comment by eugenemiretsky** [comment]
Just to make sure we're on the same page - continued the conversation in the thread of issue 323. 

This can probably be closed as it was a mistake on my end.
