### ISSUE TITLE
Proposal: Ditch old 'chef_gem cookbook' dependency

### ISSUE THREAD

**Issue by jblaine** [martinisoft/chef-rvm#333]
It's almost June of 2015.

The dependency on the chef_gem cookbook was added by @fnichol 2.5 years ago to support old versions of Chef.

It's confusing now and unnecessary baggage and complexity in an already very complex cookbook with enough troubles of its own, IMO.

I propose that the dependency on it be removed and documentation added for those running Chef that is old enough to still need it.

Comments?

**Comment by martinisoft** [comment]
Hi @jblaine 

I totally agree with you. The master branch will drop his dependency as we'll be targeting Chef 11+ in future releases.
