### ISSUE TITLE
Please update version on supermarket

### ISSUE THREAD

**Issue by brauliobo** [martinisoft/chef-rvm#334]
The version 0.9.2 is more than a year old...

**Comment by martinisoft** [comment]
Hi @brauliobo 

I've just shipped 0.9.4 which will be the last in the 0.9.x series. 1.0 will contain a few breaking changes as it's a full re-write of master, which is still currently broken (I'm updating the README shortly to reflect this fact).

**Comment by brauliobo** [comment]
@martinisoft thanks!
