### ISSUE TITLE
How to specify a configuration flag? Not shown in the docs.

### ISSUE THREAD

**Issue by heaven** [martinisoft/chef-rvm#335]
Hi, need an ability to specify configuration flag (--with-jemalloc), is it possible?

**Comment by martinisoft** [comment]
Hi @heaven 

You should be able to pass in `script_flags` to the installer LWRP according to [this line](https://github.com/martinisoft/chef-rvm/blob/8012925aa4ef9c0ead7abf2f301c9c7e279f03b7/libraries/chef_rvm_recipe_helpers.rb#L73) provided you also use the 0.9.4 version.

**Comment by heaven** [comment]
Hi, this is about ruby configuration flags, not rvm. I would expect something like:
```json
"rubies": [
  "ruby-1.9.3-p448",
  "ruby-2.1.0",
  {
    "version": "2.2.1",
    "options": "-C --with-jemalloc"
  }
]
```

**Comment by heaven** [comment]
Can you please reopen this? I need to pass --disable-binary option when installing ruby, there's no way to do so as I can see.
