### ISSUE TITLE
What is with the readme cleanup deleting pertinent information???????

### ISSUE THREAD

**Issue by dhoer** [martinisoft/chef-rvm#344]
@martinisoft What is the rational with deleting parts on how to use the cookbook but leave items like berkshelf in.  If you are using berkshelf or librarian, you probably know how to use it so that could probably be deleted.  But I don't understand why the information on how to actually use the cookbook would be deleted.

**Comment by martinisoft** [comment]
@dhoer This is for a pending re-write as the LWRP experiment never got to be completed. I can link to the README in a previous tagged release to help with documentation, but a lot of the recipe based functionality will go away. For the resource based portions, whatever stays around will get re-documented again.

**Comment by dhoer** [comment]
@martinisoft Ok, but to me chef 12 is very unstable across platforms. RVM has been around and legacy chef 11 users like me will probably not migrate to chef 12 for a while.  

If I had to choose the top 3 items to fix in RVM community cookbook, it would be:
- Documentation
- ChefSpec support
- Clearing up PR and issues

Forcing users to chef 12.5+ to use the new resource style (while much cleaner), IMHO should not be a priority at this time.
