### ISSUE TITLE
Using with vagrant - Error "Gem.source_index is deprecated, use Specification. It will be removed on or after 2011-11-01"

### ISSUE THREAD

**Issue by ni-ka** [martinisoft/chef-rvm#72]
[Wed, 29 Feb 2012 16:40:45 -0800] INFO: *** Chef 0.10.2 ***
[Wed, 29 Feb 2012 16:40:45 -0800] INFO: Setting the run_list to ["recipe[rvm]"] from JSON
[Wed, 29 Feb 2012 16:40:45 -0800] INFO: Run List is [recipe[rvm]]
[Wed, 29 Feb 2012 16:40:45 -0800] INFO: Run List expands to [rvm]
[Wed, 29 Feb 2012 16:40:45 -0800] INFO: Starting Chef Run for lucid64
[Wed, 29 Feb 2012 16:40:45 -0800] INFO: Processing gem_package[rvm] action install (rvm::default line 21)
NOTE: Gem.source_index is deprecated, use Specification. It will be removed on or after 2011-11-01.
Gem.source_index called from /opt/ruby/lib/ruby/gems/1.8/gems/chef-0.10.2/bin/../lib/chef/provider/package/rubygems.rb:2
02.

NOTE: Gem::SourceIndex#search is deprecated with no replacement. It will be removed on or after 2011-11-01.
Gem::SourceIndex#search called from /opt/ruby/lib/ruby/gems/1.8/gems/chef-0.10.2/bin/../lib/chef/provider/package/rubyge
ms.rb:76.
Hey,

I'm using chef-rvm with vagrant, and am getting the following error

    [Wed, 29 Feb 2012 16:40:45 -0800] INFO: Processing gem_package[rvm] action nothing (rvm::default line 21)
    NOTE: Gem.source_index is deprecated, use Specification. It will be removed on or after 2011-11-01.
    Gem.source_index called from /opt/ruby/lib/ruby/gems/1.8/gems/chef-0.10.2/bin/../lib/chef/provider/package/rubygems.rb:202.
    NOTE: Gem::SourceIndex#search is deprecated with no replacement. It will be removed on or after 2011-11-01.
    Gem::SourceIndex#search called from /opt/ruby/lib/ruby/gems/1.8/gems/chef-0.10.2/bin/../lib/chef/provider/package/rubygems.rb:76.
    [Wed, 29 Feb 2012 16:40:45 -0800] INFO: Chef Run complete in 0.125359 seconds
    [Wed, 29 Feb 2012 16:40:45 -0800] INFO: Running report handlers
    [Wed, 29 Feb 2012 16:40:45 -0800] INFO: Report handlers complete

Is it a chef-rvm or vagrant issue?

thx!

Nils

**Comment by cmluciano** [comment]
This has been fixed [upstream](https://github.com/mdkent/chef/commits/CHEF-2328)
